### ISSUE TITLE
BrowseEverything integration

### ISSUE THREAD

**Issue by Nimphal** [CottageLabs/willow#13]
Following https://github.com/projecthydra/browse-everything#installation 

For demo purposes, we should probably have Willow accounts on the cloud services (Dropbox, etc) and get API keys. Dropbox information has been sent around.

**Comment by Nimphal** [comment]
Integrate with 2 providers, for example 
- [ ] Dropbox
- [ ] Google Drive

**Comment by richard-jones** [comment]
I've had an initial look at this, and here is what I learned/found:

put:

    mount BrowseEverything::Engine => '/browseeverything'

in routes.rb

Add a file called "browse_everything_providers.yml" in willow/config, containing the following structure:

```yml
file_system:
  :home: /<location for server file drop>
sky_drive:
  :client_id: <your client id>
  :client_secret: <your client secret>
box:
  :client_id: <your client id>
  :client_secret: <your client secret>
  :max_upload_file_size: 5368709120
drop_box:
  :app_key: <your client id>
  :app_secret: <your app secret>
google_drive:
  :client_id: <your client id>
  :client_secret: <your client secret>
```

I only attempted to integrate the google_drive settings, which I did like this:

1. Go here: https://console.developers.google.com/cloud-resource-manager
2. Create a new project (or choose the existing Willow Demo one if possible)
3. Search (at the top) for Google Drive API
4. On the Google Drive API page, click "Enable"
5. Go through the process of setting up credentials, to get a client id and a client secret, and set the OAuth callback url (which will be [baseurl]/browseeverything/connect, so from your local machine is http://localhost:3000/browseeverything/connect
6. Put the client id and the client secret in the yml file above

If you do this, and restart Willow, you will be given the option to load a file from a cloud provider when you submit a new Work.

These are the problems that I found along the way:

* For some reason the google drive only shows me the items that are "Shared with me", rather than my actual google drive folkders
* The drive integration takes ages, at it seems to cache the full tree of drive folders on load
* Attempting to configure the other cloud providers with dummy config results in errors in the UI, but I'm not sure why

In terms of what to do next, it would be good to work out how to get the browse everything configuration to be put together during build from your local .env files, as we won't want to check the client ids and secrets into the github.

**Comment by Nimphal** [comment]
Not in the current roadmap, closing for now.
