### ISSUE TITLE
A user can't add a work to a collection

### ISSUE THREAD

**Issue by emanuil-tolev** [CottageLabs/willow#223]
1. log in as a regular depositor user
2. add a collection (works)
3. select a previously deposited (approved) work to add to collection. Willow asks which collection to add the work to. Select the collection from step 2.
4. get the following error

![image](https://user-images.githubusercontent.com/1190172/29559847-205fddc8-8728-11e7-9b43-9d96a393a93e.png)

**Comment by emanuil-tolev** [comment]
ETA to fix requested by RDSS team

**Comment by martyn-w** [comment]
I think this error is caused by an un-updated CRSF token, which causes the request to be rejected. As an immediate work-around, you can reload the "add to collection" page before clicking on submit.

**Comment by emanuil-tolev** [comment]
Can we add some kinda forced refresh there?

Also that's weird. I'd have expected it to just have the new token. Might be worth reporting to Hyrax.

**Comment by martyn-w** [comment]
This is a known issue in Hyrax: https://github.com/samvera/hyrax/issues/1191

The problem is that the page contains two CRSF tokens, one as a meta tag in the <head>, and the other as a form variable in the <form>. It seems that the form tag can lag the header tag, which causes the server to reject the request.

I'll attempt a fix...
