### ISSUE TITLE
Automate setup and configuration

### ISSUE THREAD

**Issue by Nimphal** [CottageLabs/willow#5]

**Comment by emanuil-tolev** [comment]
Production, staging (or blue/green), review (demo) and development-ready Docker orchestration with secrets management.

**Comment by Nimphal** [comment]
For the current stage of the project, I'd like to propose the following acceptance criteria for this issue:

- [ ] app runs locally
- [ ] running demo
- [ ] secrets management (implementing #35 )

**Comment by emanuil-tolev** [comment]
> secrets management (implementing #35 )

So, #35 is a private knowledge base for humans, not really suitable for server deployments to read off. E.g., it will be decrypted with a password, which an app running in a container can't really support in a secure fashion.

There's the "secrets management" of "make sure secrets are backed up and accessible to everybody who needs to have access" (the human part). There's also the "secrets management" of "private API keys, secret keys and other credentials that a running application needs to do its job automatically and securely".

An example of the 2nd meaning is a `local.cfg` file as used in Octopus, or `.env` as used in many Ruby projects.

For this issue, we need the 2nd meaning implemented somehow. #35 implements it for people, the first meaning. Feel free to call them something different to reduce confusion.

* * *

The biggest problem has been the inability to commit docker-cloud.yml since our secrets management is essentially just ENV vars in that file. However, if we start compiling that file from docker-compose.yml and .env as suggested in #94, that's probably a good enough solution for now. So basically I'm suggesting that your last acceptance criteria change from "implementing #35" to "implementing #94 and .gitignoring docker-cloud.yml in the main Willow repo".

**Comment by Nimphal** [comment]
We should probably still have docker-cloud in a versioned repo. Would a private repo do for that?

**Comment by emanuil-tolev** [comment]
> We should probably still have docker-cloud in a versioned repo. Would a private repo do for that?

I didn't want to get into too much detail on what the solution *might be* in that comment, but we do have to solve this in this issue.

I kind of see-saw between thinking we should version it, and thinking we should not. If it's actually compiled from docker-compose.yml as #94 suggests, then it's a compiled asset and doesn't need to be versioned since its "source files" are versioned and the process of compilation is versioned.

I've suggested some alternatives to achieving #94. Really, what we version depends on #94, but ultimately we will at least version our `.env` in a private repo (or at least the one to be used on demo/production infrastructure).

**Comment by Nimphal** [comment]
Since we've moved away from docker cloud, would it be okay to close this issue and open new ones relevant to current deployment plan?

**Comment by emanuil-tolev** [comment]
Yep this is full of Docker Cloud related details. Also the task checklist above https://github.com/CottageLabs/willow/issues/5#issuecomment-287338294 is complete now.
