### ISSUE TITLE
Redeploy of the stack causes images to not appear

### ISSUE THREAD

**Issue by Nimphal** [CottageLabs/willow#71]
![image](https://cloud.githubusercontent.com/assets/4950775/22257905/675295fc-e257-11e6-9893-c187d1f7d7a0.png)

**Comment by Nimphal** [comment]
Is this still relevant now that we have moved from Docker Cloud?

**Comment by Nimphal** [comment]
Ah, yes, I see in #111 that it's still a problem.

**Comment by emanuil-tolev** [comment]
It seems to be less of a problem actually. Previously the entire thing disappeared, original, preview, thumbnail (different from thumbnail) and all. So when you looked at it, you saw a "broken image" picture displayed by browsers to indicate they could not load the associated image.

The problem in #111 is "there is no image data at all associated with an object imported into the repository , which we expected to have image data". The problem could be the export process from the old Vagrant-based demo, or it could be the import process. Either way, a picture *is* actually displayed - the default image used by Willow for repository objects that never had any image data associated.

I would say this issue has been solved, as its original definition was actually:

1. upload image
2. restart stack
3. browser shows "broken image" picture and the original is nowhere to be found

@martyn-w and I tested this by uploading an image at http://willow-dev.cottagelabs.com/concern/works/v118rd525 and restarting the entire demo (multiple times, since every merge into master restarts it). As you can see, the thumbnail (on "Recently Uploaded" on the homepage), the preview (on the Work page) and the original (Download Original from the work page) are all present.

**Comment by Nimphal** [comment]
Happy to close this then :)
