### ISSUE TITLE
Run fits as a seperate docker container

### ISSUE THREAD

**Issue by anusharanganathan** [CottageLabs/willow#86]
The container would need access to Willow files (/uploads by users?).

**Comment by emanuil-tolev** [comment]
The rationale is that the versions of `openjdk-8-jre-headless` and `ca-certificates-java` that our Dockerfile was using disappeared into thin air from the Debian Jessie apt repositories. Apparently this was due to newer versions being available, the old versions having security issues, and the old versions being deleted from Debian Jessie repos.

We kind of want to avoid images starting to suddenly fail to build. It might not be completely avoidable if human action is required, but it would be nice if we could rely on some upstream maintainer to do the human action of updating the package versions for us.

@anusharanganathan suggested using the `openjdk-8-jre` Dockerfile to run fits in.
