### ISSUE TITLE
Demo app does not run

### ISSUE THREAD

**Issue by Nimphal** [CottageLabs/willow#91]
Currently the app fails to run on Docker Cloud with the following error:

```ruby
[willow-1]2017-03-06T19:14:49.134479939Z bundler: failed to load command: rake (/bundle/bin/rake)
[willow-1]2017-03-06T19:14:49.134569672Z Bundler::GemNotFound: Could not find rake-12.0.0 in any of the sources
```

**Comment by emanuil-tolev** [comment]
This only seems to happen in production. We should in general reduce the differences between dev and production, but I have been taking a look at this for now.

**Comment by emanuil-tolev** [comment]
Running `ls -al $BUNDLE_PATH/gems` in `startup_prod.sh` provides an interesting insight:
```
...
[willow-1]2017-03-15T16:33:50.932138703Z drwxr-xr-x   6 root root  4096 Jan 21 19:39 rake-11.3.0
...
```

All commands later fail with

```
[willow-1]2017-03-15T16:33:55.402966546Z Bundler::GemNotFound: Could not find rake-12.0.0 in any of the sources
```

And indeed, rake-12.0.0 is not in any of the sources, only rake-11.3.0 is. How can that be, surely we must run `bundle install` at some point?

And we do, during docker building. We:

1. run bundle install during `docker build` of the `willow` image, putting the entire contents of the bundle in the /bundle folder on the image.
2. when running the image, we mount a volume inherited from the `bundle` image over the `/bundle` directory. This happens in both the `willow` and `bundle` images.
3. now the contents of `/bundle` from the willow image's point of view are replaced, masked by whatever was on the server hosting the `/bundle` volume. On live this is `/var/lib/docker/volumes/9ab3b79b9438b459783fff8caecd3e5033f28d3da207557e8c0d9968683f3d67/_data`. The contents of that folder completely mask our `bundle install` efforts during the build step.

This is just conjecture at this point, but it looks strongly like an oops we've done. The dates are pretty strong evidence - the last time `/bundle` (the volume on the demo server) was touched was 21st Jan. That date is supposed to be today 15 Mar, when we had the most recent willow image built.

I believe what's happened here is that at some point we were running `bundle install` **during startup** of the willow image, not during build. Then we stopped doing it. The bundle started slooowly drifting and never being updated, until @Nimphal completed and merged a Rails 5 upgrade, which updated nearly everything. So then the entire app broke, since we're trying to run Rails 5 from a Rails 4 2-month old bundle.

I'm gonna run with the "bundle is not updating on production" and see how we can fix this.

# Why did this happen?

I believe this is yet another instance of using a volume to speed up the local development process - but it makes the images you produce completely unreliable since you've not baked "everything you need" into the image. Instead you're relying on the surrounding environment to give you all your Ruby libraries (or in the past - solr config, postgres initialisation SQL...). Looks like this is a bit of an anti-pattern.

## Don't mount stuff in volumes that is not actual data which will change with user actions (database tables, pictures & PDFs uploaded, etc.).
## If you mount code or libraries in volumes to speed up local development iterations, you're compromising the integrity of the resulting Docker image.
## If you want faster development, use the Docker build cache. Structure the Dockerfile so `bundle install` happens as early as reasonable and is thus cached on the vast majority of runs even as you change the Dockerfile.
## If you're working on the bundle itself, like a big library upgrade, you can mount it as a volume temporarily if it will save you hours or days. But revert to not using a volume for making a pull request!

**Comment by emanuil-tolev** [comment]
To recap, I have some suggestions on changing a particular docker building practice which makes it easy to do development, but means containers lose some integrity for production. I didn't put that very helpfully above. I have now edited my comment to reflect a suggestion to what I think is an anti-pattern (details above). All comments welcome. It might be nice for us to start a code style guide for Willow, which can start off with some of the harder Docker stuff, and expand to include Ruby, JS, testing and other implementation guidelines.

I should make absolutely clear I wasn't critising anybody's work done earlier. I've just observed a pattern that made things work inconsistently and be harder to troubleshoot, and want to change it.

**Comment by emanuil-tolev** [comment]
To recap, I have some suggestions on changing a particular docker building practice which makes it easy to do development, but means containers lose some integrity for production. I didn't put that very helpfully above. I have now edited my comment to reflect a suggestion to what I think is an anti-pattern (details above). All comments welcome. It might be nice for us to start a code style guide for Willow, which can start off with some of the harder Docker stuff, and expand to include Ruby, JS, testing and other implementation guidelines.

I should make absolutely clear I wasn't critising anybody's work done earlier. I've just observed a pattern that made things work inconsistently and be harder to troubleshoot, and want to change it.

**Comment by emanuil-tolev** [comment]
I've realised how necessary volumes are for development - you would have to rebuild the image on every save of a code file. So you definitely want the code mounted as a volume for dev.

Obviously, this creates problems in production since the code is expected to be in the image rather than pulled directly on the Docker host's disk.

The patterns above should probably be seen only as patterns for a production deployment. We'll see how we reconcile this difference.

**Comment by Nimphal** [comment]
As discussed in meeting, we are moving away from Docker Cloud, do fixing the demo on there is no longer a relevant issue. Closing.
