### ISSUE TITLE
Modifying docker-compose.yml to be identical to docker-cloud.yml 

### ISSUE THREAD

**Issue by Nimphal** [CottageLabs/willow#94]
Various problems ( #91 , solr and postgress volume issues) have arisen because docker-compose.yml and docker-cloud.yml differ greatly in some ways.

This issue is to make them identical (or near as). We can look at automating this process in a future iteration.

**Comment by emanuil-tolev** [comment]
I've had a stab at designing a possible process.

Let's say we start with these assets:

- local docker-compose.yml
- local .env (.gitignored in the main Willow repo - could be a symlink to .env that is versioned in a private repo outside of this repo)
- local docker-cloud-specific.yml which will add docker-cloud specific attributes to services defined in docker-compose.yml (such as `targetnumcontainers` which only makes sense in docker-cloud.yml)
- compile-docker-cloud-yml.py - compilation process script. Bash would probably be a bit unwieldy for YAML parsing, and every dev OS except Windows has Python installed by default.

One possible compilation process might:

1. take docker-compose.yml
2. merge in the attributes from docker-cloud-specific.yml
3. translate .env to appropriate `environment:` entries for each service in docker-compose.yml

docker-compose.yml, docker-cloud-specific.yml and compile-docker-cloud-yml.sh would be versioned right here in this repo. `.env` could be versioned in a private repository, yes.

If that feels brittle, that's because it is - really, it's just pretty hard to work around the poor support for proper secrets management in Docker Cloud. I think this is a pretty clean process. We can think about other providers or wait for Docker Cloud to introduce better secrets management - later.

**Comment by emanuil-tolev** [comment]
Another possible alternative https://docs.docker.com/docker-cloud/apps/stack-yaml-reference/#environment:

> When you use the Docker Cloud CLI to create a stack, you can use the environment variables defined locally in your shell to define those in the stack. This is useful if you don’t want to store passwords or other sensitive information in your stack file:

We could just say "do not use the Docker Cloud web UI to put in stackfiles directly - you have to use the Docker Cloud CLI". Then we see if we can't make Docker Cloud CLI use the same exact .env file that docker-compose uses for local docker start-up.

**Comment by Nimphal** [comment]
We're moving away from docker cloud, closing this.
